version: '3'

services:
  server:
    container_name: 'prospect'
    build: ./
    restart: 'always'
    volumes:
      - ./:/var/www/html
    ports:
      - "90:80"
    working_dir: /var/www/html
    networks:
      - mysql_default
networks:
  mysql_default:
    driver: default
    external: true
